name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: let's look for skip
        if: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}
        run: echo "I found the skip"
      - name: let's look for rats
        if: ${{ !contains(toJson(github.event.commits.*.message), '#rats') }}
        run: echo "I found no rats"
      - name: Who is the author
        env:
          THE_AUTHOR: ${{ toJson(github.event.commits.*.author.name) }}
          THE_URL: ${{ toJson(github.event.commits.*.url) }}
        run: echo "$THE_AUTHOR \n $THE_URL"