name: Periodic health check

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  periodic_health_check:
      runs-on: ubuntu-20.04
      steps:
        - name: Check the health of the app
          uses: jtalk/url-health-check-action@v3
          with:
            url: https://mypokedex.fly.dev/health
            max-attempts: 3
            retry-delay: 5s