name: Testing and training 

on:
  push:
    branches:
      - "**"

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: let's look for skip
        if: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}
        run: echo "I found the skip"
      - name: let's look for rats
        if: ${{ !contains(toJson(github.event.commits.*.message), '#rats') }}
        run: echo "I found no rats"
      - name: Who is the author?
        env:
          THE_AUTHOR: ${{ toJson(github.event.commits[0].author.name) }}
        run: echo "The author is $THE_AUTHOR"
      - name: Check the health of the app
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://mypokedex.fly.dev/health
          max-attempts: 3
          retry-delay: 5s